### ISSUE TITLE
intolerances

### ISSUE THREAD

**Issue by sniperle** [trmendes/FoodRestrictions-moving-to-gitlab#3]
Thanks for the good idea and the app.

I have a feature request, add food intolerances please, like:
- Lactose intolerance - https://en.m.wikipedia.org/wiki/Lactose_intolerance
- Fructose malabsorption - https://en.m.wikipedia.org/wiki/Fructose_malabsorption
- Gluten intolerance (Coeliac disease) - https://en.m.wikipedia.org/wiki/Coeliac_disease
- more ?

**Comment by trmendes** [comment]
I will ASD your ideas to the app as soon as I have a computer.

**Comment by trmendes** [comment]
moving this project to gitlab :D
