### ISSUE TITLE
Possibility to hide/show icons

### ISSUE THREAD

**Issue by Stopi** [trmendes/FoodRestrictions-moving-to-gitlab#7]
Can you please do that ?
if so, then it would be easy for you to add several things like eggs, nuts, etc. 
I need eggs but don't need nuts so if I can choose icons to show, it would be nice.

**Comment by Stopi** [comment]
Ok, I realized I wasn't clear. I want to be able to show some icons with or without a cross on it, and to hide others, in the icon view.

**Comment by trmendes** [comment]
As soon as I have a computer.

**Comment by trmendes** [comment]
moving this project to gitlab :D
