### ISSUE TITLE
please expand marine and river food restrictions

### ISSUE THREAD

**Issue by qwertyuser1983** [trmendes/FoodRestrictions-moving-to-gitlab#8]
I am included,

I can eat fishes and most marine foods, fishes, clams, oysters, abalones, and nories, except

That I cant eat anything high in histamine content, like crabs, shrimps, prawns, lobsters.

And I really love fish :) 

So, at least, please, 

separate fishes, prawns, crabs, and clams ;)

**Comment by trmendes** [comment]
I need someone to help me to draw the icons.

**Comment by trmendes** [comment]
moving this project to gitlab :D
